# Generated by Django 4.2.24 on 2025-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
