# Generated by Django 4.2.24 on 2025-10-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api_app', '0004_forgotpasswordrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
