# Generated by Django 4.2.24 on 2025-10-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api_app', '0002_alter_staff_date_of_joining'),
        ('receptionist_api_app', '0001_initial'),
        ('ambulance_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AECase',
            fields=[
                ('ae_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=20)),
                ('triage_level', models.CharField(choices=[('Critical', 'Critical'), ('Serious', 'Serious'), ('Stable', 'Stable')], max_length=20)),
                ('brought_by', models.CharField(blank=True, max_length=50)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Under Treatment', 'Under Treatment'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Deceased', 'Deceased')], default='Under Treatment', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulance_api_app.ambulance')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptionist_api_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TempPatient',
            fields=[
                ('temp_patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('approx_age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('identification_marks', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Merged', 'Merged'), ('Deceased', 'Deceased')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyTreatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.TextField(blank=True)),
                ('medicine_list', models.TextField(blank=True)),
                ('lab_tests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ae_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ae_api_app.aecase')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_api_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='aecase',
            name='temp_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ae_api_app.temppatient'),
        ),
    ]
