# Generated by Django 4.2.24 on 2025-09-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNotes',
            fields=[
                ('consultation_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.CharField(max_length=100, unique=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLab',
            fields=[
                ('prescription_lab_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_lab_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLabDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMed',
            fields=[
                ('prescription_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_med_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
