# Generated by Django 5.2.6 on 2025-09-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api_app', '0001_initial'),
        ('receptionist_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionLabDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMed',
            fields=[
                ('prescription_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_med_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationNotes',
            fields=[
                ('consultation_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.CharField(max_length=100, unique=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist_api_app.appointment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to='admin_api_app.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionLab',
            fields=[
                ('prescription_lab_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_lab_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_lab', to='receptionist_api_app.appointment')),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_lab', to='doctor_api_app.consultationnotes')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions_lab', to='admin_api_app.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
