# Generated by Django 5.2.7 on 2025-10-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api_app', '0001_initial'),
        ('doctor_api_app', '0001_initial'),
        ('labtech_api_app', '0001_initial'),
        ('pharmacist_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionlabdetail',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtech_api_app.labtest'),
        ),
        migrations.AddField(
            model_name='prescriptionlabdetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_api_app.prescriptionlab'),
        ),
        migrations.AddField(
            model_name='prescriptionlab',
            name='lab_tests',
            field=models.ManyToManyField(related_name='lab_prescriptions', through='doctor_api_app.PrescriptionLabDetail', to='labtech_api_app.labtest'),
        ),
        migrations.AddField(
            model_name='prescriptionmed',
            name='consultation_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_med', to='doctor_api_app.consultationnotes'),
        ),
        migrations.AddField(
            model_name='prescriptionmed',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions_med', to='admin_api_app.staff'),
        ),
        migrations.AddField(
            model_name='prescriptionmeddetail',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacist_api_app.medicine'),
        ),
        migrations.AddField(
            model_name='prescriptionmeddetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_api_app.prescriptionmed'),
        ),
        migrations.AddField(
            model_name='prescriptionmed',
            name='medicines',
            field=models.ManyToManyField(related_name='medicine_prescriptions', through='doctor_api_app.PrescriptionMedDetail', to='pharmacist_api_app.medicine'),
        ),
    ]
