# Generated by Django 4.2.24 on 2025-09-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_auto_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("patient_name", models.CharField(max_length=255)),
                ("patient_email", models.EmailField(max_length=254)),
                ("patient_age", models.PositiveIntegerField()),
                ("patient_gender", models.CharField(max_length=10)),
                ("patient_blood_group", models.CharField(max_length=5)),
                ("patient_phone", models.CharField(max_length=15)),
                ("patient_address", models.TextField()),
                ("patient_reg_date", models.DateField()),
                ("patient_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecBilling",
            fields=[
                ("rec_bill_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "billing_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("billing_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receptionist_api_app.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_api_app.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_auto_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("appointment_id", models.CharField(max_length=100, unique=True)),
                ("appoinment_date", models.DateField()),
                ("appoinment_time", models.TimeField()),
                (
                    "appoinment_status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("appoinment_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receptionist_api_app.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_api_app.staff",
                    ),
                ),
            ],
        ),
    ]
