# Generated by Django 4.2.24 on 2025-10-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
