from .models import ConsultationNotes, PrescriptionLab, PrescriptionMed
from rest_framework import serializers
from django.db import IntegrityError, transaction
from .models import (
    ConsultationNotes,
    PrescriptionMed,
    PrescriptionMedDetail,
    PrescriptionLab,
    PrescriptionLabDetail,
)
from receptionist_api_app.models import appointments
from admin_api_app.models import staff
from pharmacist_api_app.models import pharmacist_medicine
from labtech_api_app.models import lab_tests



# -------------------------
# PrescriptionMedDetail Serializer (join/through model)
# -------------------------
class PrescriptionMedDetailSerializer(serializers.ModelSerializer):
    # medicine is a FK to pharmacist_medicine; accept its PK in requests.
    medicine = serializers.PrimaryKeyRelatedField(queryset=pharmacist_medicine.objects.all())

    class Meta:
        model = PrescriptionMedDetail
        # Expose id so client can identify existing detail rows, plus business fields.
        fields = ["id", "medicine", "dosage", "quantity", "instructions"]

    # Validate quantity is a positive integer
    def validate_quantity(self, value):
        if value is None or value <= 0:
            raise serializers.ValidationError("Quantity must be a positive integer.")
        return value
    
# -------------------------
# PrescriptionMed Serializer (nested create/update)
# -------------------------
class PrescriptionMedSerializer(serializers.ModelSerializer):
    # Use PK fields for related models so client sends IDs only (lightweight).
    consultation_id = serializers.PrimaryKeyRelatedField(queryset=ConsultationNotes.objects.all())
    appointment_id = serializers.PrimaryKeyRelatedField(queryset=appointments.objects.all())
    staff_id = serializers.PrimaryKeyRelatedField(queryset=staff.objects.all())

    # `details` is write-only input for nested creation/update of PrescriptionMedDetail rows.
    # It expects a list of objects matching PrescriptionMedDetailSerializer.
    details = PrescriptionMedDetailSerializer(many=True, write_only=True)

    # `details_out` is the read-only representation of detail rows when returning a prescription.
    # We point the source to the reverse accessor generated by Django:
    # prescription.prescriptionmeddetail_set.all() -> source 'prescriptionmeddetail_set'.
    details_out = PrescriptionMedDetailSerializer(source="prescriptionmeddetail_set", many=True, read_only=True)

    class Meta:
        model = PrescriptionMed
        fields = [
            "prescription_auto_id",   # DB auto PK
            "prescription_med_id",    # generated code like PMED001
            "consultation_id",
            "appointment_id",
            "staff_id",
            "created_at",
            "details",    # write-only nested input
            "details_out" # read-only nested output
        ]
        # auto-generated and timestamps should be read-only
        read_only_fields = ("prescription_auto_id", "prescription_med_id", "created_at")

    # Object-level validation example: require at least one medicine detail on create.
    def validate(self, attrs):
        details = attrs.get("details", [])
        if not details:
            raise serializers.ValidationError("At least one medicine must be provided.")
        medicine_ids = [detail["medicine"].id for detail in details]
        if len(medicine_ids) != len(set(medicine_ids)):
            raise serializers.ValidationError("Duplicate medicines are not allowed.")
        # Ensure consultation and appointment match
        if attrs.get("consultation_id") and attrs.get("appointment_id"):
            if attrs["consultation_id"].appointment_id != attrs["appointment_id"]:
                raise serializers.ValidationError("Consultation and appointment do not match.")
        return attrs
    # create() handles nested creation of PrescriptionMedDetail rows.
    @transaction.atomic
    def create(self, validated_data):
        details_data = validated_data.pop("details", [])
        try:
            prescription = PrescriptionMed.objects.create(**validated_data)
            for detail in details_data:
                PrescriptionMedDetail.objects.create(prescription=prescription, **detail)
            return prescription
        except IntegrityError as e:
            raise serializers.ValidationError({"error": f"Database error: {str(e)}"})
        except Exception as e:
            raise serializers.ValidationError({"error": f"Unexpected error: {str(e)}"})



    # update() handles updates to the prescription and replaces detail rows with incoming on


# -------------------------
# PrescriptionLabDetail Serializer (join/through model)
# -------------------------
class PrescriptionLabDetailSerializer(serializers.ModelSerializer):
    # lab_test is a FK to lab_tests; accept its PK.
    lab_test = serializers.PrimaryKeyRelatedField(queryset=lab_tests.objects.all())

    class Meta:
        model = PrescriptionLabDetail
        fields = ["id", "lab_test", "instructions"]


# -------------------------
# PrescriptionLab Serializer (nested create/update)
# -------------------------
class PrescriptionLabSerializer(serializers.ModelSerializer):
    consultation_id = serializers.PrimaryKeyRelatedField(queryset=ConsultationNotes.objects.all())
    appointment_id = serializers.PrimaryKeyRelatedField(queryset=appointments.objects.all())
    staff_id = serializers.PrimaryKeyRelatedField(queryset=staff.objects.all())

    # Nested input for creating/updating lab test prescriptions
    details = PrescriptionLabDetailSerializer(many=True, write_only=True)
    # Nested read-only output; source is reverse accessor prescription.prescriptionlabdetail_set
    details_out = PrescriptionLabDetailSerializer(source="prescriptionlabdetail_set", many=True, read_only=True)

    class Meta:
        model = PrescriptionLab
        fields = [
            "prescription_lab_auto_id",
            "prescription_lab_id",
            "consultation_id",
            "appointment_id",
            "staff_id",
            "created_at",
            "details",
            "details_out",
        ]
        read_only_fields = ("prescription_lab_auto_id", "prescription_lab_id", "created_at")

    # validate ensures at least one lab test is provided on create
    def validate(self, attrs):
        details = attrs.get("details", [])
        if not details:
            raise serializers.ValidationError("At least one lab test must be provided.")
        
        lab_ids = [detail["lab_test"].id for detail in details]
        if len(lab_ids) != len(set(lab_ids)):
            raise serializers.ValidationError("Duplicate lab tests are not allowed.")
        
        if attrs.get("consultation_id") and attrs.get("appointment_id"):
            if attrs["consultation_id"].appointment_id != attrs["appointment_id"]:
                raise serializers.ValidationError("Consultation and appointment do not match.")
        
        if attrs.get("consultation_id") and attrs.get("staff_id"):
            if attrs["consultation_id"].staff_id != attrs["staff_id"]:
                raise serializers.ValidationError("Staff must match consultation doctor.")
        
        return attrs
    @transaction.atomic
    def create(self, validated_data):
        details_data = validated_data.pop("details", [])
        try:
            prescription = PrescriptionLab.objects.create(**validated_data)
            for detail in details_data:
                PrescriptionLabDetail.objects.create(prescription=prescription, **detail)
            return prescription
        except IntegrityError as e:
            raise serializers.ValidationError({"error": f"Database error: {str(e)}"})
        except Exception as e:
            raise serializers.ValidationError({"error": f"Unexpected error: {str(e)}"})

# -------------------------
# ConsultationNotes Serializer
# -------------------------
class ConsultationNotesSerializer(serializers.ModelSerializer):
    # Use PrimaryKeyRelatedField so API accepts/returns the appointment's primary key (ID)
    # rather than embedding the entire appointment object.
    appointment_id = serializers.PrimaryKeyRelatedField(
        queryset=appointments.objects.all()
    )
    # Same for staff: accept/validate an integer staff PK.
    staff_id = serializers.PrimaryKeyRelatedField(
        queryset=staff.objects.all()
    )
    
    prescriptions_med = PrescriptionMedSerializer(
        source="prescriptionmed_set",  # Django reverse relation
        many=True,
        read_only=True
    )
    prescriptions_lab = PrescriptionLabSerializer(
        source="prescriptionlab_set",  # Django reverse relation
        many=True,
        read_only=True
    )

    class Meta:
        # Model this serializer is for
        model = ConsultationNotes
        # fields to expose via API
        fields = [
            "consultation_auto_id",   # internal AutoField primary key
            "consultation_id",        # the generated code like CONS001
            "appointment_id",
            "staff_id",
            "symptoms",
            "diagnosis",
            "notes",
            "created_at",
        ]
        # These fields are set by the model/save logic, don't allow client to set them
        read_only_fields = ("consultation_auto_id", "consultation_id", "created_at")

    # Field-level validation: ensures symptoms has some meaningful length.
    def validate_symptoms(self, value):
        if value is None or len(value.strip()) < 3:
            raise serializers.ValidationError("Provide a brief description of symptoms (3+ chars).")
        return value

    # Object-level validation: ensure diagnosis or notes is present (example business rule).
    def validate(self, data):
        # This runs after individual field validators. The API must have either a diagnosis
        # or notes (so consultations aren't empty).
        diagnosis = data.get("diagnosis", "")
        notes = data.get("notes", "")
        if (diagnosis is None or str(diagnosis).strip() == "") and (notes is None or str(notes).strip() == ""):
            raise serializers.ValidationError("Either 'diagnosis' or 'notes' must be provided.")
        return data

