# Generated by Django 4.2.24 on 2025-10-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulance_api_app.ambulance')),
            ],
        ),
    ]
