# Generated by Django 5.2.7 on 2025-10-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulance_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('driver', models.OneToOneField(limit_choices_to={'user__role': 'AMB'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_driver', to='admin_api_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ambulance_api_app.ambulance')),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'user__role': 'AMB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests_assigned', to='admin_api_app.staff')),
                ('created_by', models.ForeignKey(limit_choices_to={'user__role': 'REC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests_created', to='admin_api_app.staff')),
            ],
        ),
    ]
