# Generated by Django 4.2.24 on 2025-10-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api_app', '0003_leaverequest'),
        ('ambulance_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='driver_phone',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'user__role': 'AMB'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_driver', to='admin_api_app.staff'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role': 'AMB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests_assigned', to='admin_api_app.staff'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'user__role': 'REC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests_created', to='admin_api_app.staff'),
        ),
        migrations.AlterField(
            model_name='ambulancerequest',
            name='assigned_ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ambulance_api_app.ambulance'),
        ),
    ]
