# Generated by Django 4.2.24 on 2025-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_api_app', '0002_remove_ambulance_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancerequest',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
