# Generated by Django 4.2.24 on 2025-10-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api_app', '0004_forgotpasswordrequest'),
        ('ambulance_api_app', '0003_ambulancerequest_completed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.OneToOneField(limit_choices_to={'user__role': 'AMB'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_driver', to='admin_api_app.staff'),
        ),
    ]
