# Generated by Django 4.2.24 on 2025-09-22 03:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor_api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestCategory",
            fields=[
                ("CategoryId", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "LabTestId",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("LabTestName", models.CharField(max_length=100)),
                ("Rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "Max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("Is_Active", models.BooleanField(default=True)),
                ("Created_On", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "CategoryId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labtech_api_app.labtestcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                ("ResultId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Status",
                    models.CharField(
                        choices=[("Pending", "pending"), ("Completed", "completed")],
                        max_length=50,
                    ),
                ),
                (
                    "result_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "LabPrescriptionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor_api_app.prescriptionlab",
                    ),
                ),
                (
                    "TestId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labtech_api_app.labtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabBilling",
            fields=[
                ("BillId", models.AutoField(primary_key=True, serialize=False)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "BillingDate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "LabPrescriptionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor_api_app.prescriptionlab",
                    ),
                ),
            ],
        ),
    ]
