# Generated by Django 4.2.24 on 2025-10-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
