# Generated by Django 4.2.24 on 2025-10-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_failed_login_attempts_user_lock_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('REC', 'Receptionist'), ('DOC', 'Doctor'), ('LAB', 'Lab Technician'), ('PHARM', 'Pharmacist'), ('AMB', 'Ambulance Driver')], default='ADMIN', max_length=10),
        ),
    ]
